// <auto-generated/>
public static class MusicSoundSetupIds
{
    public const string test = "test";
    public const string testSound = "testSound";
    public const string testMusic = "testMusic";
}
