using System.IO;
using System.Text;
using Sounds;
using UnityEditor;
using UnityEngine;

namespace Utiles.CodGenerator
{
    public static class SoundIDsGenerator
    {
        private const string _rootDirectory = "Assets/Scripts/AutoGenerated";

        public static void GenerateFromConfig(SoundDataSetup setup)
        {
            if (setup is null)
            {
                Debug.LogError("Setup can't be null");

                return;
            }

            var className = setup.name.Replace(" ", "") + "Ids";
            var outputPath = Path.Combine(_rootDirectory, className + ".g.cs");

            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"public static class {className}");
            sb.AppendLine("{");

            foreach (var soundPair in setup.SoundDataList)
            {
                if (string.IsNullOrWhiteSpace(soundPair.SoundId))
                {
                    continue;
                }
                
                string safeName = MakeSafe(soundPair.SoundId);
                
                sb.AppendLine($"    public const string {safeName} = \"{soundPair.SoundId}\";");
            }
            
            sb.AppendLine("}");
            
            Directory.CreateDirectory(_rootDirectory);
            File.WriteAllText(outputPath, sb.ToString());

            AssetDatabase.Refresh();
        }

        private static string MakeSafe(string id)
        {
            string sanitized = id.Replace(" ", "_").Replace("-", "_");

            if (char.IsDigit(sanitized[0]))
            {
                sanitized = "_" + sanitized;
            }
            
            return sanitized;
        }
    }
}